name: watchx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:  # logo
  android: "icon"
  ios: true
  image_path: "lib/Images/Logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/Images/Logo.png
    - lib/Images/watchaura.jpg    #  watch images
    - lib/Images/watchblack.jpg   #
    - lib/Images/watchwhite.jpg   #
    - lib/Images/watchshiny.jpg   #